[versions]
version = "2026.01.01-SNAPSHOT"

[libraries]
catalog = { group = "com.jacknic.catalog", name = "catalog", version.ref = "version" }

[bundles]


[plugins]

publish = { id = "com.vanniktech.maven.publish", version = "0.35.0" }